#!/usr/bin/env python
import time
import os,sys
import argparse
import subprocess
import string
import random

#--user dependent paths
path    ='/w/halla-scshelf2102/moller12gev/tasneemm'
wdir    ='%s/remoll'%path
macrodir='macros'
macro   ='showermax_event_for_piongen'
njob	='1'

template="""#!/bin/bash
#SBATCH --account=halla
#SBATCH --mem-per-cpu=500
#SBATCH --ntasks=1
#SBATCH --job-name=<name>
#SBATCH --partition=production
#SBATCH --output=<wdir>/jobs/out/<name>_16032025.out
#SBATCH --error=<wdir>/jobs/out/<name>_16032025.err
#SBATCH --mail-user=tasneemm@jlab.org
#SBATCH --mail-type=END
#SBATCH --time=8:00:00

build/remoll -o /volatile/halla/moller12gev/tasneemm/showermax_events_for_piongen_<njob>.root <macrodir>/<macro>.mac
"""


template=template.replace('<path>',path)
template=template.replace('<wdir>',wdir)
template=template.replace('<macrodir>',macrodir)
template=template.replace('<macro>',macro)


def checkdir(path):
  if not os.path.exists(path):
    os.makedirs(path)

#def gen_xml(track,nn):
def gen_xml(nn):
    fname='remoll_%s'%(macro+nn)
    xml=template[:]
    xml=xml.replace('<name>',fname)
    #xml=xml.replace('<track>',track)
    xml=xml.replace('<njob>',nn)

    F=open('current.sh','w')
    F.writelines(xml)
    F.close()

def pexit(msg):
    print(msg)
    sys.exit()

if __name__=='__main__':


    ap = argparse.ArgumentParser()
    msg =" 0: gen test sh"
    msg+=" 1: submit jobs(s)"
    ap.add_argument('task'             ,type=int,help=msg)
    ap.add_argument('-n','--njobs'     ,type=int,default=1 ,help='number of jobs')
    args = ap.parse_args()

    checkdir('%s/jobs/out'%(wdir))
    
    if    args.task==0:
          #track='debug'
          #gen_xml(track,nn=str(args.njobs))
          gen_xml(nn=str(args.njobs))

    elif  args.task==1:
          cnt=0
          #partition='production'
          while 1:
              cnt+=1 
              print (cnt)
              #gen_xml(track,nn=str(cnt))
              gen_xml(nn=str(cnt))
              try:
                  #jsub='/site/bin/sbatch'
                  jsub='sbatch'
                  os.system('%s current.sh'%jsub)
                  time.sleep(2)
              except:
                  continue
              if cnt==args.njobs: break
